### ISSUE TITLE
Unnecessary ping request may block the task deletion from the DB if there was no finalization URL given

### ISSUE THREAD

**Issue by th-wyns** [SenseNet/sn-taskmanagement#2]
File: AgentHub.cs
Method: TaskFinished

The ApplicationHandler.SendPingRequest tries to ping the webserver regardless I provided a finalization URL or not. 
If I start a new task without a finalization URL and valid application URL (because I don't have/need one), the ping will block the removement of the task.

![2016-10-10_1436](https://cloud.githubusercontent.com/assets/19415638/21115997/f24e3fd2-c0b3-11e6-8fdb-af60a7c917e5.png)

**Comment by tusmester** [comment]
I agree, tasks do not necessarily have a finalize URL, it is not an error if a task does not have one. DB cleanup should be executed regardless of the existence of a finalize URL.

**Comment by tusmester** [comment]
Thank you @iviczl for fixing this in pull request #3
